{"frames":[{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"as.factor(a)","line_number":0},{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"factor(x)","line_number":0},{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"order(y)","line_number":0}],"message":"Error in order(y) : 類型 'list' 尚未在 'orderVector1' 中實作\n"}